# Generated by Django 5.1.15 on 2026-09-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusarea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='focus/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Home page hero background. Falls back to img/hero.svg.', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_image',
            field=models.ImageField(blank=True, help_text='Photo beside the founding story block on the home page.', null=True, upload_to='site/'),
        ),
    ]
