# Generated by Django 5.1.15 on 2026-09-07 20:06

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_focusarea_image_sitesettings_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusarea',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full description shown on the focus area page.'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Untick to hide this from the public site. Staff still see it.', verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_section_page',
            field=models.BooleanField(default=False, help_text='Set by seed_content for the pages behind a fixed route. Their path is what links them to that route, so changing it detaches the page and the built-in wording comes back.', verbose_name='Section landing page'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, help_text='One or two sentences shown by Google and by Facebook, LinkedIn and WhatsApp link previews. Falls back to the intro when left empty.', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Untick to hide this from the public site. Staff still see it.', verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='One or two sentences shown by Google and by Facebook, LinkedIn and WhatsApp link previews. Falls back to the intro when left empty.', max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='The main content of the page.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Wide photograph behind the page heading.', null=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='intro',
            field=models.TextField(blank=True, help_text='Short paragraph under the page heading.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
