# Generated by Django 5.1.15 on 2026-09-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_focusarea_body_page_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Innovations for Rural Empowerment in Access to Community Health and Equity', max_length=255),
        ),
    ]
