# Generated by Django 5.1.15 on 2026-09-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesettings_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_office',
            field=models.BooleanField(default=False, help_text='iREACHE LASTMILE has an office here.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='info@ireachelastmile.org', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_blurb',
            field=models.TextField(default='iREACHE LASTMILE works alongside government, communities and partners to build primary health care that reaches everyone, everywhere.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_body',
            field=models.TextField(default='iREACHE LASTMILE designs responsive primary health care systems so that life-saving products and services reach the communities hardest to reach.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_prefix',
            field=models.CharField(default='iREACHE LASTMILE transforms', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='legal_line',
            field=models.CharField(default='iREACHE LASTMILE is a registered not-for-profit organisation', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='organisation_name',
            field=models.CharField(default='iREACHE LASTMILE', max_length=120),
        ),
    ]
