# Generated by Django 5.1.15 on 2026-09-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_location_is_office_alter_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Sierra Leone · Eastern Province · 2026', help_text='Small line printed above the hero headline.', max_length=160),
        ),
        migrations.AddField(
            model_name='stat',
            name='caption',
            field=models.CharField(blank=True, help_text="Short qualifier under a hero figure, e.g. 'Target < 300'.", max_length=120),
        ),
        migrations.AddField(
            model_name='stat',
            name='group',
            field=models.CharField(choices=[('hero', 'Home page hero'), ('band', 'Impact band')], default='band', max_length=8),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_body',
            field=models.TextField(default='iREACHE LASTMILE connects three systems that have never governed community health together — traditional authority, government, and community intelligence — through 6,800 ProcCHWs reaching every last-mile household every month.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline',
            field=models.CharField(default="Sierra Leone's communities", max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_prefix',
            field=models.CharField(default='Building the health system', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_rotating_words',
            field=models.CharField(default='have always deserved.', help_text='Closing line of the hero headline. Several comma separated phrases are cycled; a single one stays put.', max_length=255),
        ),
    ]
